# Generated by Django 3.2.18 on 2023-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0006_tweets_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
